package: external
generate:
  client: false
  chi-server: true
  models: true
  embedded-spec: true
  strict-server: true
import-mapping:
  # ./packageA/spec.yaml: github.com/deepmap/oapi-codegen/internal/test/externalref/packageA
  # ./packageB/spec.yaml: github.com/deepmap/oapi-codegen/internal/test/externalref/packageB
output: internal/platform/handlers/external/server.gen.go
output-options:
  skip-prune: true