// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CreateAssetRequestType.
const (
	CreateAssetRequestTypeJit          CreateAssetRequestType = "jit"
	CreateAssetRequestTypePaste        CreateAssetRequestType = "paste"
	CreateAssetRequestTypePolicy       CreateAssetRequestType = "policy"
	CreateAssetRequestTypeSecret       CreateAssetRequestType = "secret"
	CreateAssetRequestTypeService      CreateAssetRequestType = "service"
	CreateAssetRequestTypeServiceGroup CreateAssetRequestType = "service_group"
	CreateAssetRequestTypeVault        CreateAssetRequestType = "vault"
)

// Valid indicates whether the value is a known member of the CreateAssetRequestType enum.
func (e CreateAssetRequestType) Valid() bool {
	switch e {
	case CreateAssetRequestTypeJit:
		return true
	case CreateAssetRequestTypePaste:
		return true
	case CreateAssetRequestTypePolicy:
		return true
	case CreateAssetRequestTypeSecret:
		return true
	case CreateAssetRequestTypeService:
		return true
	case CreateAssetRequestTypeServiceGroup:
		return true
	case CreateAssetRequestTypeVault:
		return true
	default:
		return false
	}
}

// Defines values for PolicySpecActions.
const (
	PolicySpecActionsConnect      PolicySpecActions = "connect"
	PolicySpecActionsDelete       PolicySpecActions = "delete"
	PolicySpecActionsManagePolicy PolicySpecActions = "manage_policy"
	PolicySpecActionsRead         PolicySpecActions = "read"
	PolicySpecActionsRotate       PolicySpecActions = "rotate"
	PolicySpecActionsView         PolicySpecActions = "view"
)

// Valid indicates whether the value is a known member of the PolicySpecActions enum.
func (e PolicySpecActions) Valid() bool {
	switch e {
	case PolicySpecActionsConnect:
		return true
	case PolicySpecActionsDelete:
		return true
	case PolicySpecActionsManagePolicy:
		return true
	case PolicySpecActionsRead:
		return true
	case PolicySpecActionsRotate:
		return true
	case PolicySpecActionsView:
		return true
	default:
		return false
	}
}

// Defines values for ServiceSpecProtocol.
const (
	Https    ServiceSpecProtocol = "https"
	Mysql    ServiceSpecProtocol = "mysql"
	Postgres ServiceSpecProtocol = "postgres"
	Rdp      ServiceSpecProtocol = "rdp"
	Ssh      ServiceSpecProtocol = "ssh"
)

// Valid indicates whether the value is a known member of the ServiceSpecProtocol enum.
func (e ServiceSpecProtocol) Valid() bool {
	switch e {
	case Https:
		return true
	case Mysql:
		return true
	case Postgres:
		return true
	case Rdp:
		return true
	case Ssh:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active UserStatus = "active"
	Locked UserStatus = "locked"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Locked:
		return true
	default:
		return false
	}
}

// Defines values for VaultSpecVaultType.
const (
	Personal VaultSpecVaultType = "personal"
	Shared   VaultSpecVaultType = "shared"
	System   VaultSpecVaultType = "system"
)

// Valid indicates whether the value is a known member of the VaultSpecVaultType enum.
func (e VaultSpecVaultType) Valid() bool {
	switch e {
	case Personal:
		return true
	case Shared:
		return true
	case System:
		return true
	default:
		return false
	}
}

// Defines values for PostAssetsIdActionsJSONBodyActionType.
const (
	PostAssetsIdActionsJSONBodyActionTypeCheckIn  PostAssetsIdActionsJSONBodyActionType = "check_in"
	PostAssetsIdActionsJSONBodyActionTypeCheckOut PostAssetsIdActionsJSONBodyActionType = "check_out"
	PostAssetsIdActionsJSONBodyActionTypeElevate  PostAssetsIdActionsJSONBodyActionType = "elevate"
	PostAssetsIdActionsJSONBodyActionTypeRotate   PostAssetsIdActionsJSONBodyActionType = "rotate"
)

// Valid indicates whether the value is a known member of the PostAssetsIdActionsJSONBodyActionType enum.
func (e PostAssetsIdActionsJSONBodyActionType) Valid() bool {
	switch e {
	case PostAssetsIdActionsJSONBodyActionTypeCheckIn:
		return true
	case PostAssetsIdActionsJSONBodyActionTypeCheckOut:
		return true
	case PostAssetsIdActionsJSONBodyActionTypeElevate:
		return true
	case PostAssetsIdActionsJSONBodyActionTypeRotate:
		return true
	default:
		return false
	}
}

// Defines values for GetIdentityUsersParamsView.
const (
	Full    GetIdentityUsersParamsView = "full"
	Summary GetIdentityUsersParamsView = "summary"
)

// Valid indicates whether the value is a known member of the GetIdentityUsersParamsView enum.
func (e GetIdentityUsersParamsView) Valid() bool {
	switch e {
	case Full:
		return true
	case Summary:
		return true
	default:
		return false
	}
}

// Defines values for PostVaultsVaultIdMembershipsJSONBodyMemberType.
const (
	PostVaultsVaultIdMembershipsJSONBodyMemberTypeUser  PostVaultsVaultIdMembershipsJSONBodyMemberType = "user"
	PostVaultsVaultIdMembershipsJSONBodyMemberTypeVault PostVaultsVaultIdMembershipsJSONBodyMemberType = "vault"
)

// Valid indicates whether the value is a known member of the PostVaultsVaultIdMembershipsJSONBodyMemberType enum.
func (e PostVaultsVaultIdMembershipsJSONBodyMemberType) Valid() bool {
	switch e {
	case PostVaultsVaultIdMembershipsJSONBodyMemberTypeUser:
		return true
	case PostVaultsVaultIdMembershipsJSONBodyMemberTypeVault:
		return true
	default:
		return false
	}
}

// Defines values for PostVaultsVaultIdMembershipsJSONBodyRole.
const (
	Manager PostVaultsVaultIdMembershipsJSONBodyRole = "manager"
	Owner   PostVaultsVaultIdMembershipsJSONBodyRole = "owner"
	Viewer  PostVaultsVaultIdMembershipsJSONBodyRole = "viewer"
)

// Valid indicates whether the value is a known member of the PostVaultsVaultIdMembershipsJSONBodyRole enum.
func (e PostVaultsVaultIdMembershipsJSONBodyRole) Valid() bool {
	switch e {
	case Manager:
		return true
	case Owner:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Asset defines model for Asset.
type Asset struct {
	CreatedAt *time.Time              `json:"created_at,omitempty"`
	Id        *openapi_types.UUID     `json:"id,omitempty"`
	Name      *string                 `json:"name,omitempty"`
	OwnerId   *openapi_types.UUID     `json:"owner_id,omitempty"`
	ParentId  *openapi_types.UUID     `json:"parent_id,omitempty"`
	Spec      *map[string]interface{} `json:"spec,omitempty"`
	Type      *string                 `json:"type,omitempty"`
}

// AssetList defines model for AssetList.
type AssetList struct {
	Data *[]Asset        `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	Action     *string             `json:"action,omitempty"`
	ActorId    *openapi_types.UUID `json:"actor_id,omitempty"`
	ResourceId *openapi_types.UUID `json:"resource_id,omitempty"`
	Success    *bool               `json:"success,omitempty"`
	Timestamp  *time.Time          `json:"timestamp,omitempty"`
}

// CreateAssetRequest defines model for CreateAssetRequest.
type CreateAssetRequest struct {
	Name string                  `json:"name"`
	Spec CreateAssetRequest_Spec `json:"spec"`
	Type CreateAssetRequestType  `json:"type"`
}

// CreateAssetRequest_Spec defines model for CreateAssetRequest.Spec.
type CreateAssetRequest_Spec struct {
	union json.RawMessage
}

// CreateAssetRequestType defines model for CreateAssetRequest.Type.
type CreateAssetRequestType string

// JITSpec defines model for JITSpec.
type JITSpec struct {
	ApproverGroup   *openapi_types.UUID `json:"approver_group,omitempty"`
	DurationMinutes int                 `json:"duration_minutes"`
	Justification   string              `json:"justification"`
	TargetAssetId   openapi_types.UUID  `json:"target_asset_id"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
	Total  *int `json:"total,omitempty"`
}

// PasteSpec defines model for PasteSpec.
type PasteSpec struct {
	BurnAfterRead *bool `json:"burn_after_read,omitempty"`

	// Content Ephemeral encrypted text
	Content    string `json:"content"`
	TtlSeconds int    `json:"ttl_seconds"`
}

// PolicySpec defines model for PolicySpec.
type PolicySpec struct {
	Actions []PolicySpecActions `json:"actions"`
	Objects struct {
		AssetIds *[]openapi_types.UUID   `json:"asset_ids,omitempty"`
		Tags     *map[string]interface{} `json:"tags,omitempty"`
	} `json:"objects"`
	Subjects struct {
		Groups *[]openapi_types.UUID `json:"groups,omitempty"`
		Users  *[]openapi_types.UUID `json:"users,omitempty"`
	} `json:"subjects"`
}

// PolicySpecActions defines model for PolicySpec.Actions.
type PolicySpecActions string

// SecretSpec defines model for SecretSpec.
type SecretSpec struct {
	// EncryptedPayload Base64 encrypted blob
	EncryptedPayload string             `json:"encrypted_payload"`
	MimeType         *string            `json:"mime_type,omitempty"`
	RotationEnabled  *bool              `json:"rotation_enabled,omitempty"`
	VaultId          openapi_types.UUID `json:"vault_id"`
}

// ServiceGroupSpec defines model for ServiceGroupSpec.
type ServiceGroupSpec struct {
	// Tags List of tags
	Tags *[]string `json:"tags,omitempty"`
}

// ServiceSpec defines model for ServiceSpec.
type ServiceSpec struct {
	Endpoint string              `json:"endpoint"`
	Protocol ServiceSpecProtocol `json:"protocol"`

	// Tags Comma-separated list of tags
	Tags *string `json:"tags,omitempty"`
}

// ServiceSpecProtocol defines model for ServiceSpec.Protocol.
type ServiceSpecProtocol string

// UpdateUserProfileRequest defines model for UpdateUserProfileRequest.
type UpdateUserProfileRequest struct {
	DisplayName          *string                 `json:"display_name,omitempty"`
	Email                *string                 `json:"email,omitempty"`
	FirstName            *string                 `json:"first_name,omitempty"`
	GroupIds             *[]openapi_types.UUID   `json:"group_ids,omitempty"`
	LastName             *string                 `json:"last_name,omitempty"`
	NotificationSettings *map[string]interface{} `json:"notification_settings,omitempty"`
}

// User defines model for User.
type User struct {
	DisplayName          *string                 `json:"display_name,omitempty"`
	Email                string                  `json:"email"`
	FirstName            *string                 `json:"first_name,omitempty"`
	Id                   openapi_types.UUID      `json:"id"`
	LastName             *string                 `json:"last_name,omitempty"`
	NotificationSettings *map[string]interface{} `json:"notification_settings,omitempty"`
	Status               *UserStatus             `json:"status,omitempty"`
	Username             string                  `json:"username"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// UserGroup defines model for UserGroup.
type UserGroup struct {
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// UserGroupList defines model for UserGroupList.
type UserGroupList struct {
	Data *[]UserGroup    `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// VaultSpec defines model for VaultSpec.
type VaultSpec struct {
	EncryptionLevel *string            `json:"encryption_level,omitempty"`
	RecoveryEnabled *bool              `json:"recovery_enabled,omitempty"`
	VaultType       VaultSpecVaultType `json:"vault_type"`
}

// VaultSpecVaultType defines model for VaultSpec.VaultType.
type VaultSpecVaultType string

// PatchAdminConfigJSONBody defines parameters for PatchAdminConfig.
type PatchAdminConfigJSONBody struct {
	JwtTtl             *int      `json:"jwt_ttl,omitempty"`
	NetworkWhitelist   *[]string `json:"network_whitelist,omitempty"`
	RebuildPolicyCache *bool     `json:"rebuild_policy_cache,omitempty"`
}

// GetAssetsParams defines parameters for GetAssets.
type GetAssetsParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Type Filter by asset type (service, service_group, vault, secret, policy, paste, jit)
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// ParentId Filter by parent asset ID
	ParentId *openapi_types.UUID `form:"parent_id,omitempty" json:"parent_id,omitempty"`

	// AssetId Filter by specific asset ID
	AssetId *openapi_types.UUID `form:"asset_id,omitempty" json:"asset_id,omitempty"`

	// Limit Maximum number of assets to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of assets to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostAssetsIdActionsJSONBody defines parameters for PostAssetsIdActions.
type PostAssetsIdActionsJSONBody struct {
	ActionType PostAssetsIdActionsJSONBodyActionType `json:"action_type"`
	Parameters *map[string]interface{}               `json:"parameters,omitempty"`
}

// PostAssetsIdActionsJSONBodyActionType defines parameters for PostAssetsIdActions.
type PostAssetsIdActionsJSONBodyActionType string

// GetAuditLogsParams defines parameters for GetAuditLogs.
type GetAuditLogsParams struct {
	ActorId    *openapi_types.UUID `form:"actor_id,omitempty" json:"actor_id,omitempty"`
	ResourceId *openapi_types.UUID `form:"resource_id,omitempty" json:"resource_id,omitempty"`
	From       *time.Time          `form:"from,omitempty" json:"from,omitempty"`
}

// GetIdentityGroupsParams defines parameters for GetIdentityGroups.
type GetIdentityGroupsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostIdentityGroupsJSONBody defines parameters for PostIdentityGroups.
type PostIdentityGroupsJSONBody struct {
	Name string `json:"name"`
}

// GetIdentityUsersParams defines parameters for GetIdentityUsers.
type GetIdentityUsersParams struct {
	// UserId Filter by specific user ID
	UserId *openapi_types.UUID `form:"user_id,omitempty" json:"user_id,omitempty"`

	// CurrentUser Return current authenticated user
	CurrentUser *bool `form:"current_user,omitempty" json:"current_user,omitempty"`

	// View Level of detail (summary returns basic info, full includes profile fields)
	View *GetIdentityUsersParamsView `form:"view,omitempty" json:"view,omitempty"`
}

// GetIdentityUsersParamsView defines parameters for GetIdentityUsers.
type GetIdentityUsersParamsView string

// PostIdentityUsersJSONBody defines parameters for PostIdentityUsers.
type PostIdentityUsersJSONBody struct {
	Email    string                `json:"email"`
	GroupIds *[]openapi_types.UUID `json:"group_ids,omitempty"`
	Password string                `json:"password"`
	Username string                `json:"username"`
}

// PostVaultsVaultIdMembershipsJSONBody defines parameters for PostVaultsVaultIdMemberships.
type PostVaultsVaultIdMembershipsJSONBody struct {
	MemberId   openapi_types.UUID                             `json:"member_id"`
	MemberType PostVaultsVaultIdMembershipsJSONBodyMemberType `json:"member_type"`
	Role       PostVaultsVaultIdMembershipsJSONBodyRole       `json:"role"`
}

// PostVaultsVaultIdMembershipsJSONBodyMemberType defines parameters for PostVaultsVaultIdMemberships.
type PostVaultsVaultIdMembershipsJSONBodyMemberType string

// PostVaultsVaultIdMembershipsJSONBodyRole defines parameters for PostVaultsVaultIdMemberships.
type PostVaultsVaultIdMembershipsJSONBodyRole string

// PatchAdminConfigJSONRequestBody defines body for PatchAdminConfig for application/json ContentType.
type PatchAdminConfigJSONRequestBody PatchAdminConfigJSONBody

// PostAssetsJSONRequestBody defines body for PostAssets for application/json ContentType.
type PostAssetsJSONRequestBody = CreateAssetRequest

// PostAssetsIdActionsJSONRequestBody defines body for PostAssetsIdActions for application/json ContentType.
type PostAssetsIdActionsJSONRequestBody PostAssetsIdActionsJSONBody

// PostIdentityGroupsJSONRequestBody defines body for PostIdentityGroups for application/json ContentType.
type PostIdentityGroupsJSONRequestBody PostIdentityGroupsJSONBody

// PostIdentityUsersJSONRequestBody defines body for PostIdentityUsers for application/json ContentType.
type PostIdentityUsersJSONRequestBody PostIdentityUsersJSONBody

// PutIdentityUsersJSONRequestBody defines body for PutIdentityUsers for application/json ContentType.
type PutIdentityUsersJSONRequestBody = UpdateUserProfileRequest

// PostVaultsVaultIdMembershipsJSONRequestBody defines body for PostVaultsVaultIdMemberships for application/json ContentType.
type PostVaultsVaultIdMembershipsJSONRequestBody PostVaultsVaultIdMembershipsJSONBody

// AsServiceSpec returns the union data inside the CreateAssetRequest_Spec as a ServiceSpec
func (t CreateAssetRequest_Spec) AsServiceSpec() (ServiceSpec, error) {
	var body ServiceSpec
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServiceSpec overwrites any union data inside the CreateAssetRequest_Spec as the provided ServiceSpec
func (t *CreateAssetRequest_Spec) FromServiceSpec(v ServiceSpec) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServiceSpec performs a merge with any union data inside the CreateAssetRequest_Spec, using the provided ServiceSpec
func (t *CreateAssetRequest_Spec) MergeServiceSpec(v ServiceSpec) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsServiceGroupSpec returns the union data inside the CreateAssetRequest_Spec as a ServiceGroupSpec
func (t CreateAssetRequest_Spec) AsServiceGroupSpec() (ServiceGroupSpec, error) {
	var body ServiceGroupSpec
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServiceGroupSpec overwrites any union data inside the CreateAssetRequest_Spec as the provided ServiceGroupSpec
func (t *CreateAssetRequest_Spec) FromServiceGroupSpec(v ServiceGroupSpec) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServiceGroupSpec performs a merge with any union data inside the CreateAssetRequest_Spec, using the provided ServiceGroupSpec
func (t *CreateAssetRequest_Spec) MergeServiceGroupSpec(v ServiceGroupSpec) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVaultSpec returns the union data inside the CreateAssetRequest_Spec as a VaultSpec
func (t CreateAssetRequest_Spec) AsVaultSpec() (VaultSpec, error) {
	var body VaultSpec
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVaultSpec overwrites any union data inside the CreateAssetRequest_Spec as the provided VaultSpec
func (t *CreateAssetRequest_Spec) FromVaultSpec(v VaultSpec) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVaultSpec performs a merge with any union data inside the CreateAssetRequest_Spec, using the provided VaultSpec
func (t *CreateAssetRequest_Spec) MergeVaultSpec(v VaultSpec) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSecretSpec returns the union data inside the CreateAssetRequest_Spec as a SecretSpec
func (t CreateAssetRequest_Spec) AsSecretSpec() (SecretSpec, error) {
	var body SecretSpec
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSecretSpec overwrites any union data inside the CreateAssetRequest_Spec as the provided SecretSpec
func (t *CreateAssetRequest_Spec) FromSecretSpec(v SecretSpec) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSecretSpec performs a merge with any union data inside the CreateAssetRequest_Spec, using the provided SecretSpec
func (t *CreateAssetRequest_Spec) MergeSecretSpec(v SecretSpec) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPolicySpec returns the union data inside the CreateAssetRequest_Spec as a PolicySpec
func (t CreateAssetRequest_Spec) AsPolicySpec() (PolicySpec, error) {
	var body PolicySpec
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPolicySpec overwrites any union data inside the CreateAssetRequest_Spec as the provided PolicySpec
func (t *CreateAssetRequest_Spec) FromPolicySpec(v PolicySpec) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePolicySpec performs a merge with any union data inside the CreateAssetRequest_Spec, using the provided PolicySpec
func (t *CreateAssetRequest_Spec) MergePolicySpec(v PolicySpec) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPasteSpec returns the union data inside the CreateAssetRequest_Spec as a PasteSpec
func (t CreateAssetRequest_Spec) AsPasteSpec() (PasteSpec, error) {
	var body PasteSpec
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPasteSpec overwrites any union data inside the CreateAssetRequest_Spec as the provided PasteSpec
func (t *CreateAssetRequest_Spec) FromPasteSpec(v PasteSpec) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePasteSpec performs a merge with any union data inside the CreateAssetRequest_Spec, using the provided PasteSpec
func (t *CreateAssetRequest_Spec) MergePasteSpec(v PasteSpec) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJITSpec returns the union data inside the CreateAssetRequest_Spec as a JITSpec
func (t CreateAssetRequest_Spec) AsJITSpec() (JITSpec, error) {
	var body JITSpec
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJITSpec overwrites any union data inside the CreateAssetRequest_Spec as the provided JITSpec
func (t *CreateAssetRequest_Spec) FromJITSpec(v JITSpec) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJITSpec performs a merge with any union data inside the CreateAssetRequest_Spec, using the provided JITSpec
func (t *CreateAssetRequest_Spec) MergeJITSpec(v JITSpec) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateAssetRequest_Spec) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateAssetRequest_Spec) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAdminConfig request
	GetAdminConfig(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchAdminConfigWithBody request with any body
	PatchAdminConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchAdminConfig(ctx context.Context, body PatchAdminConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAssets request
	GetAssets(ctx context.Context, params *GetAssetsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAssetsWithBody request with any body
	PostAssetsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAssets(ctx context.Context, body PostAssetsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAssetsIdActionsWithBody request with any body
	PostAssetsIdActionsWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAssetsIdActions(ctx context.Context, id openapi_types.UUID, body PostAssetsIdActionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAuditLogs request
	GetAuditLogs(ctx context.Context, params *GetAuditLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIdentityGroups request
	GetIdentityGroups(ctx context.Context, params *GetIdentityGroupsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostIdentityGroupsWithBody request with any body
	PostIdentityGroupsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostIdentityGroups(ctx context.Context, body PostIdentityGroupsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIdentityUsers request
	GetIdentityUsers(ctx context.Context, params *GetIdentityUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostIdentityUsersWithBody request with any body
	PostIdentityUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostIdentityUsers(ctx context.Context, body PostIdentityUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutIdentityUsersWithBody request with any body
	PutIdentityUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutIdentityUsers(ctx context.Context, body PutIdentityUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVaultsVaultIdMemberships request
	GetVaultsVaultIdMemberships(ctx context.Context, vaultId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVaultsVaultIdMembershipsWithBody request with any body
	PostVaultsVaultIdMembershipsWithBody(ctx context.Context, vaultId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostVaultsVaultIdMemberships(ctx context.Context, vaultId openapi_types.UUID, body PostVaultsVaultIdMembershipsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAdminConfig(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminConfigRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchAdminConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchAdminConfigRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchAdminConfig(ctx context.Context, body PatchAdminConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchAdminConfigRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAssets(ctx context.Context, params *GetAssetsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAssetsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAssetsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAssetsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAssets(ctx context.Context, body PostAssetsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAssetsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAssetsIdActionsWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAssetsIdActionsRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAssetsIdActions(ctx context.Context, id openapi_types.UUID, body PostAssetsIdActionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAssetsIdActionsRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAuditLogs(ctx context.Context, params *GetAuditLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuditLogsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetIdentityGroups(ctx context.Context, params *GetIdentityGroupsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIdentityGroupsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostIdentityGroupsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostIdentityGroupsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostIdentityGroups(ctx context.Context, body PostIdentityGroupsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostIdentityGroupsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetIdentityUsers(ctx context.Context, params *GetIdentityUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIdentityUsersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostIdentityUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostIdentityUsersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostIdentityUsers(ctx context.Context, body PostIdentityUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostIdentityUsersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutIdentityUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutIdentityUsersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutIdentityUsers(ctx context.Context, body PutIdentityUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutIdentityUsersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVaultsVaultIdMemberships(ctx context.Context, vaultId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVaultsVaultIdMembershipsRequest(c.Server, vaultId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVaultsVaultIdMembershipsWithBody(ctx context.Context, vaultId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVaultsVaultIdMembershipsRequestWithBody(c.Server, vaultId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVaultsVaultIdMemberships(ctx context.Context, vaultId openapi_types.UUID, body PostVaultsVaultIdMembershipsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVaultsVaultIdMembershipsRequest(c.Server, vaultId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAdminConfigRequest generates requests for GetAdminConfig
func NewGetAdminConfigRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchAdminConfigRequest calls the generic PatchAdminConfig builder with application/json body
func NewPatchAdminConfigRequest(server string, body PatchAdminConfigJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchAdminConfigRequestWithBody(server, "application/json", bodyReader)
}

// NewPatchAdminConfigRequestWithBody generates requests for PatchAdminConfig with any type of body
func NewPatchAdminConfigRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAssetsRequest generates requests for GetAssets
func NewGetAssetsRequest(server string, params *GetAssetsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/assets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Q != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "q", *params.Q, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ParentId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "parent_id", *params.ParentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AssetId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "asset_id", *params.AssetId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAssetsRequest calls the generic PostAssets builder with application/json body
func NewPostAssetsRequest(server string, body PostAssetsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAssetsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAssetsRequestWithBody generates requests for PostAssets with any type of body
func NewPostAssetsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/assets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAssetsIdActionsRequest calls the generic PostAssetsIdActions builder with application/json body
func NewPostAssetsIdActionsRequest(server string, id openapi_types.UUID, body PostAssetsIdActionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAssetsIdActionsRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPostAssetsIdActionsRequestWithBody generates requests for PostAssetsIdActions with any type of body
func NewPostAssetsIdActionsRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/assets/%s/actions", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAuditLogsRequest generates requests for GetAuditLogs
func NewGetAuditLogsRequest(server string, params *GetAuditLogsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/audit/logs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ActorId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "actor_id", *params.ActorId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ResourceId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "resource_id", *params.ResourceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.From != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "from", *params.From, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetIdentityGroupsRequest generates requests for GetIdentityGroups
func NewGetIdentityGroupsRequest(server string, params *GetIdentityGroupsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/identity/groups")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostIdentityGroupsRequest calls the generic PostIdentityGroups builder with application/json body
func NewPostIdentityGroupsRequest(server string, body PostIdentityGroupsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostIdentityGroupsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostIdentityGroupsRequestWithBody generates requests for PostIdentityGroups with any type of body
func NewPostIdentityGroupsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/identity/groups")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetIdentityUsersRequest generates requests for GetIdentityUsers
func NewGetIdentityUsersRequest(server string, params *GetIdentityUsersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/identity/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.UserId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "user_id", *params.UserId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CurrentUser != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "current_user", *params.CurrentUser, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.View != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "view", *params.View, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostIdentityUsersRequest calls the generic PostIdentityUsers builder with application/json body
func NewPostIdentityUsersRequest(server string, body PostIdentityUsersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostIdentityUsersRequestWithBody(server, "application/json", bodyReader)
}

// NewPostIdentityUsersRequestWithBody generates requests for PostIdentityUsers with any type of body
func NewPostIdentityUsersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/identity/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutIdentityUsersRequest calls the generic PutIdentityUsers builder with application/json body
func NewPutIdentityUsersRequest(server string, body PutIdentityUsersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutIdentityUsersRequestWithBody(server, "application/json", bodyReader)
}

// NewPutIdentityUsersRequestWithBody generates requests for PutIdentityUsers with any type of body
func NewPutIdentityUsersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/identity/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetVaultsVaultIdMembershipsRequest generates requests for GetVaultsVaultIdMemberships
func NewGetVaultsVaultIdMembershipsRequest(server string, vaultId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "vaultId", vaultId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vaults/%s/memberships", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostVaultsVaultIdMembershipsRequest calls the generic PostVaultsVaultIdMemberships builder with application/json body
func NewPostVaultsVaultIdMembershipsRequest(server string, vaultId openapi_types.UUID, body PostVaultsVaultIdMembershipsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostVaultsVaultIdMembershipsRequestWithBody(server, vaultId, "application/json", bodyReader)
}

// NewPostVaultsVaultIdMembershipsRequestWithBody generates requests for PostVaultsVaultIdMemberships with any type of body
func NewPostVaultsVaultIdMembershipsRequestWithBody(server string, vaultId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "vaultId", vaultId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vaults/%s/memberships", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAdminConfigWithResponse request
	GetAdminConfigWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminConfigResponse, error)

	// PatchAdminConfigWithBodyWithResponse request with any body
	PatchAdminConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchAdminConfigResponse, error)

	PatchAdminConfigWithResponse(ctx context.Context, body PatchAdminConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchAdminConfigResponse, error)

	// GetAssetsWithResponse request
	GetAssetsWithResponse(ctx context.Context, params *GetAssetsParams, reqEditors ...RequestEditorFn) (*GetAssetsResponse, error)

	// PostAssetsWithBodyWithResponse request with any body
	PostAssetsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAssetsResponse, error)

	PostAssetsWithResponse(ctx context.Context, body PostAssetsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAssetsResponse, error)

	// PostAssetsIdActionsWithBodyWithResponse request with any body
	PostAssetsIdActionsWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAssetsIdActionsResponse, error)

	PostAssetsIdActionsWithResponse(ctx context.Context, id openapi_types.UUID, body PostAssetsIdActionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAssetsIdActionsResponse, error)

	// GetAuditLogsWithResponse request
	GetAuditLogsWithResponse(ctx context.Context, params *GetAuditLogsParams, reqEditors ...RequestEditorFn) (*GetAuditLogsResponse, error)

	// GetIdentityGroupsWithResponse request
	GetIdentityGroupsWithResponse(ctx context.Context, params *GetIdentityGroupsParams, reqEditors ...RequestEditorFn) (*GetIdentityGroupsResponse, error)

	// PostIdentityGroupsWithBodyWithResponse request with any body
	PostIdentityGroupsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostIdentityGroupsResponse, error)

	PostIdentityGroupsWithResponse(ctx context.Context, body PostIdentityGroupsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostIdentityGroupsResponse, error)

	// GetIdentityUsersWithResponse request
	GetIdentityUsersWithResponse(ctx context.Context, params *GetIdentityUsersParams, reqEditors ...RequestEditorFn) (*GetIdentityUsersResponse, error)

	// PostIdentityUsersWithBodyWithResponse request with any body
	PostIdentityUsersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostIdentityUsersResponse, error)

	PostIdentityUsersWithResponse(ctx context.Context, body PostIdentityUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostIdentityUsersResponse, error)

	// PutIdentityUsersWithBodyWithResponse request with any body
	PutIdentityUsersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutIdentityUsersResponse, error)

	PutIdentityUsersWithResponse(ctx context.Context, body PutIdentityUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*PutIdentityUsersResponse, error)

	// GetVaultsVaultIdMembershipsWithResponse request
	GetVaultsVaultIdMembershipsWithResponse(ctx context.Context, vaultId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetVaultsVaultIdMembershipsResponse, error)

	// PostVaultsVaultIdMembershipsWithBodyWithResponse request with any body
	PostVaultsVaultIdMembershipsWithBodyWithResponse(ctx context.Context, vaultId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVaultsVaultIdMembershipsResponse, error)

	PostVaultsVaultIdMembershipsWithResponse(ctx context.Context, vaultId openapi_types.UUID, body PostVaultsVaultIdMembershipsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVaultsVaultIdMembershipsResponse, error)
}

type GetAdminConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetAdminConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchAdminConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PatchAdminConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchAdminConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAssetsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AssetList
}

// Status returns HTTPResponse.Status
func (r GetAssetsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAssetsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAssetsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Asset
}

// Status returns HTTPResponse.Status
func (r PostAssetsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAssetsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAssetsIdActionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostAssetsIdActionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAssetsIdActionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAuditLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]AuditEntry
}

// Status returns HTTPResponse.Status
func (r GetAuditLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuditLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetIdentityGroupsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserGroupList
}

// Status returns HTTPResponse.Status
func (r GetIdentityGroupsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIdentityGroupsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostIdentityGroupsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostIdentityGroupsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostIdentityGroupsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetIdentityUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]User
}

// Status returns HTTPResponse.Status
func (r GetIdentityUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIdentityUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostIdentityUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostIdentityUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostIdentityUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutIdentityUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
}

// Status returns HTTPResponse.Status
func (r PutIdentityUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutIdentityUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVaultsVaultIdMembershipsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetVaultsVaultIdMembershipsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVaultsVaultIdMembershipsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVaultsVaultIdMembershipsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostVaultsVaultIdMembershipsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVaultsVaultIdMembershipsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAdminConfigWithResponse request returning *GetAdminConfigResponse
func (c *ClientWithResponses) GetAdminConfigWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetAdminConfigResponse, error) {
	rsp, err := c.GetAdminConfig(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminConfigResponse(rsp)
}

// PatchAdminConfigWithBodyWithResponse request with arbitrary body returning *PatchAdminConfigResponse
func (c *ClientWithResponses) PatchAdminConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchAdminConfigResponse, error) {
	rsp, err := c.PatchAdminConfigWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchAdminConfigResponse(rsp)
}

func (c *ClientWithResponses) PatchAdminConfigWithResponse(ctx context.Context, body PatchAdminConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchAdminConfigResponse, error) {
	rsp, err := c.PatchAdminConfig(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchAdminConfigResponse(rsp)
}

// GetAssetsWithResponse request returning *GetAssetsResponse
func (c *ClientWithResponses) GetAssetsWithResponse(ctx context.Context, params *GetAssetsParams, reqEditors ...RequestEditorFn) (*GetAssetsResponse, error) {
	rsp, err := c.GetAssets(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAssetsResponse(rsp)
}

// PostAssetsWithBodyWithResponse request with arbitrary body returning *PostAssetsResponse
func (c *ClientWithResponses) PostAssetsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAssetsResponse, error) {
	rsp, err := c.PostAssetsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAssetsResponse(rsp)
}

func (c *ClientWithResponses) PostAssetsWithResponse(ctx context.Context, body PostAssetsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAssetsResponse, error) {
	rsp, err := c.PostAssets(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAssetsResponse(rsp)
}

// PostAssetsIdActionsWithBodyWithResponse request with arbitrary body returning *PostAssetsIdActionsResponse
func (c *ClientWithResponses) PostAssetsIdActionsWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAssetsIdActionsResponse, error) {
	rsp, err := c.PostAssetsIdActionsWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAssetsIdActionsResponse(rsp)
}

func (c *ClientWithResponses) PostAssetsIdActionsWithResponse(ctx context.Context, id openapi_types.UUID, body PostAssetsIdActionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAssetsIdActionsResponse, error) {
	rsp, err := c.PostAssetsIdActions(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAssetsIdActionsResponse(rsp)
}

// GetAuditLogsWithResponse request returning *GetAuditLogsResponse
func (c *ClientWithResponses) GetAuditLogsWithResponse(ctx context.Context, params *GetAuditLogsParams, reqEditors ...RequestEditorFn) (*GetAuditLogsResponse, error) {
	rsp, err := c.GetAuditLogs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuditLogsResponse(rsp)
}

// GetIdentityGroupsWithResponse request returning *GetIdentityGroupsResponse
func (c *ClientWithResponses) GetIdentityGroupsWithResponse(ctx context.Context, params *GetIdentityGroupsParams, reqEditors ...RequestEditorFn) (*GetIdentityGroupsResponse, error) {
	rsp, err := c.GetIdentityGroups(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIdentityGroupsResponse(rsp)
}

// PostIdentityGroupsWithBodyWithResponse request with arbitrary body returning *PostIdentityGroupsResponse
func (c *ClientWithResponses) PostIdentityGroupsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostIdentityGroupsResponse, error) {
	rsp, err := c.PostIdentityGroupsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostIdentityGroupsResponse(rsp)
}

func (c *ClientWithResponses) PostIdentityGroupsWithResponse(ctx context.Context, body PostIdentityGroupsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostIdentityGroupsResponse, error) {
	rsp, err := c.PostIdentityGroups(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostIdentityGroupsResponse(rsp)
}

// GetIdentityUsersWithResponse request returning *GetIdentityUsersResponse
func (c *ClientWithResponses) GetIdentityUsersWithResponse(ctx context.Context, params *GetIdentityUsersParams, reqEditors ...RequestEditorFn) (*GetIdentityUsersResponse, error) {
	rsp, err := c.GetIdentityUsers(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIdentityUsersResponse(rsp)
}

// PostIdentityUsersWithBodyWithResponse request with arbitrary body returning *PostIdentityUsersResponse
func (c *ClientWithResponses) PostIdentityUsersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostIdentityUsersResponse, error) {
	rsp, err := c.PostIdentityUsersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostIdentityUsersResponse(rsp)
}

func (c *ClientWithResponses) PostIdentityUsersWithResponse(ctx context.Context, body PostIdentityUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostIdentityUsersResponse, error) {
	rsp, err := c.PostIdentityUsers(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostIdentityUsersResponse(rsp)
}

// PutIdentityUsersWithBodyWithResponse request with arbitrary body returning *PutIdentityUsersResponse
func (c *ClientWithResponses) PutIdentityUsersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutIdentityUsersResponse, error) {
	rsp, err := c.PutIdentityUsersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutIdentityUsersResponse(rsp)
}

func (c *ClientWithResponses) PutIdentityUsersWithResponse(ctx context.Context, body PutIdentityUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*PutIdentityUsersResponse, error) {
	rsp, err := c.PutIdentityUsers(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutIdentityUsersResponse(rsp)
}

// GetVaultsVaultIdMembershipsWithResponse request returning *GetVaultsVaultIdMembershipsResponse
func (c *ClientWithResponses) GetVaultsVaultIdMembershipsWithResponse(ctx context.Context, vaultId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetVaultsVaultIdMembershipsResponse, error) {
	rsp, err := c.GetVaultsVaultIdMemberships(ctx, vaultId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVaultsVaultIdMembershipsResponse(rsp)
}

// PostVaultsVaultIdMembershipsWithBodyWithResponse request with arbitrary body returning *PostVaultsVaultIdMembershipsResponse
func (c *ClientWithResponses) PostVaultsVaultIdMembershipsWithBodyWithResponse(ctx context.Context, vaultId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostVaultsVaultIdMembershipsResponse, error) {
	rsp, err := c.PostVaultsVaultIdMembershipsWithBody(ctx, vaultId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVaultsVaultIdMembershipsResponse(rsp)
}

func (c *ClientWithResponses) PostVaultsVaultIdMembershipsWithResponse(ctx context.Context, vaultId openapi_types.UUID, body PostVaultsVaultIdMembershipsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostVaultsVaultIdMembershipsResponse, error) {
	rsp, err := c.PostVaultsVaultIdMemberships(ctx, vaultId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVaultsVaultIdMembershipsResponse(rsp)
}

// ParseGetAdminConfigResponse parses an HTTP response from a GetAdminConfigWithResponse call
func ParseGetAdminConfigResponse(rsp *http.Response) (*GetAdminConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePatchAdminConfigResponse parses an HTTP response from a PatchAdminConfigWithResponse call
func ParsePatchAdminConfigResponse(rsp *http.Response) (*PatchAdminConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchAdminConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetAssetsResponse parses an HTTP response from a GetAssetsWithResponse call
func ParseGetAssetsResponse(rsp *http.Response) (*GetAssetsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAssetsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AssetList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostAssetsResponse parses an HTTP response from a PostAssetsWithResponse call
func ParsePostAssetsResponse(rsp *http.Response) (*PostAssetsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAssetsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Asset
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParsePostAssetsIdActionsResponse parses an HTTP response from a PostAssetsIdActionsWithResponse call
func ParsePostAssetsIdActionsResponse(rsp *http.Response) (*PostAssetsIdActionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAssetsIdActionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetAuditLogsResponse parses an HTTP response from a GetAuditLogsWithResponse call
func ParseGetAuditLogsResponse(rsp *http.Response) (*GetAuditLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuditLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AuditEntry
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetIdentityGroupsResponse parses an HTTP response from a GetIdentityGroupsWithResponse call
func ParseGetIdentityGroupsResponse(rsp *http.Response) (*GetIdentityGroupsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIdentityGroupsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserGroupList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostIdentityGroupsResponse parses an HTTP response from a PostIdentityGroupsWithResponse call
func ParsePostIdentityGroupsResponse(rsp *http.Response) (*PostIdentityGroupsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostIdentityGroupsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetIdentityUsersResponse parses an HTTP response from a GetIdentityUsersWithResponse call
func ParseGetIdentityUsersResponse(rsp *http.Response) (*GetIdentityUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIdentityUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostIdentityUsersResponse parses an HTTP response from a PostIdentityUsersWithResponse call
func ParsePostIdentityUsersResponse(rsp *http.Response) (*PostIdentityUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostIdentityUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePutIdentityUsersResponse parses an HTTP response from a PutIdentityUsersWithResponse call
func ParsePutIdentityUsersResponse(rsp *http.Response) (*PutIdentityUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutIdentityUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetVaultsVaultIdMembershipsResponse parses an HTTP response from a GetVaultsVaultIdMembershipsWithResponse call
func ParseGetVaultsVaultIdMembershipsResponse(rsp *http.Response) (*GetVaultsVaultIdMembershipsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVaultsVaultIdMembershipsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostVaultsVaultIdMembershipsResponse parses an HTTP response from a PostVaultsVaultIdMembershipsWithResponse call
func ParsePostVaultsVaultIdMembershipsResponse(rsp *http.Response) (*PostVaultsVaultIdMembershipsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVaultsVaultIdMembershipsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xa3W/bOBL/VwjeAU0BxU6yu33I06Wfl+32kmua9iE1DFoa20wpUuFHUiPw/37gUJJl",
	"i4qVxF3cUxRpyBnO/OaTvqepygslQVpDj++pSeeQM3w8MQasfyi0KkBbDvg61cAsZGOG36ZK5/6JZszC",
	"vuU50ITaRQH0mBqruZzRZUJ5tkbrHM9iZJLl4AlbH9SdBD3uuUvBNEjbQS2dEGwigB5b7SCy2hSQNmRQ",
	"k2tIrf8QXrSEq780SFFzf3ET0V7GLPN/uYUcX/xTw5Qe038MV3YYlkYYBgusODCt2cL/n0PY5aHF52zG",
	"JbNcyU+eOi6oy7h9J61etCVlqV8bNQdLreptDg1GOZ1CX3rj0hSMaTCeKCWASVQEz8FYlhd9sRc79RtE",
	"MCr3M9w4iNmpgiL8ZHnh4ULPtcoc6oS8ZZZNmIlCvcKPknA2pcdXDxvpAvQtT+HCL1omvWg/aOWKXgu+",
	"Midsz61TDf1Iz5Xg6aIfKTO239H+PP0S6EYNRwPpcnp8RU04N02qp/HMq4Am9NYfEN978WlCCxTOP3jW",
	"NKHX3NJRDBQabhzXkHkGaOuSqDTgKAKbSsi2pxSFVregS7n6gDxzGl1znHPpbNimhtrh0UG9hEsLM9B+",
	"zbUzlk95yjr90jI9AztmHtn93G1DE5sbRATdlCOmqY3Q01KY4Dm3jRM0Dqmm0zLrtL9ZZZmIfVpGZajA",
	"12I/cVqO2dSCHmtgqKYMpoil9azQCDypkhakDbQm1bwIVqDvijnkoJkgIFO9KCxkxMJPG7O6tWJsIFUy",
	"Wzf4b68OIhbfsE0lwfo2UfWvXLQjqpu1FFQ52i2HO+qZMm/5VEnpN0yoVpahN2UgAB9yJtkMxqW7jWJH",
	"3chYQToTEajE2rpIWx1oc3/LZiaStmPIMK5LFvTfZwriDOhnbdEWeQMItfxJbc2VfmN4aET31pFr0I4L",
	"thCq8oYmwl8zA69+b8B7ItQkdo6c5zCuonftUdR7w7AQjMtoeeDB5QMMSF+XZfG8j5H+SSGtXplEzhrX",
	"1kaabemswtq6mny9R9SU4Ndk5dxXfjWGUq+0QvOcafSZGiCPBkQtZJdNs0LxEKxW9cvhweBg8MfgMFoy",
	"a2VVqsRa2jVz7/uZT7Rzawt/qHxhbgTmWWNnGkzc9aPqeaPynO0bKJj27QMRHepCbSXZJKk0tc3A9Wkb",
	"x4jZ9bLwZeKlAX2u1ZQL6Kz9Mm4KwRbjznYEcsZF9MuUa2O7F2KAeX6wE+whJlKt0vPYgLVc9o6NXj1/",
	"p0J69gS7OXBCjWXWreU8H0FvfUoTKv0BWRTQPqR3MN/AIkpfk1d6GXUo+kNVLm5ou+k397tupmMSI+mD",
	"Uu6gmV2d+Bc2tKuWpyvTeYwIuAWxnqQYmP2jP17tz9I83sSmvsJfNLPU1poxpJ7NdqYAbZRkPoyaOfNm",
	"SKhZGAv59k6lseMoViYYSJ3mdnHhVVYWu8A06BNn56v/3lfY+fPbF88dqb3s+HV1fh/26dJvzOVU4fBH",
	"ScvSkFmCz+OnfxUZw659kKq8AtQxPX97gm/JhSsKpdFC61nhUvIph4y8fv+enJyfDsiZTudgrM8Rhrzl",
	"Jqg9IacZSMvtguz5o3y7eJkQJjMSShtD9s7R8i8H3+WlAUNenCuxyJUu5jwlJ6FKekGmSpOzAkJHwwSx",
	"zPwwg+9Yl3Bbdvn8lguYQUZK2T9hrZuDtOQCzeQF9c0naBMOcXRw9GpwODjAOrcAyQpOj+lvg4PBb9iK",
	"2jlaYsiynMthquSUz7DcDI2OqiQ6zegx/QD2xNO9CWQ4PymUNMGaRwcH7dSaOq29eGHnsmHDwyJHUobE",
	"NYTgZKKJjavRclTl7iuKItARTtNsOm+Lee5fbwqK+fS1yhYVVMqOiRWFKOPz8NqEsBa8uu2m13d2bK2I",
	"d4AS7J3SP8Z3c25BlDGpbx3lJZw4LrKybxmnLJ1DrN6MlOBrjugdftnHMkE3JJQeWR8DGJdj1XNc1ise",
	"4UhPzpWxTuOgYsNIy4QOsY0yD6IqUOB8lOVgsU25uqfcC3rjAEut0nFvqqjAohlk85jvubCgyWRBUAzi",
	"F5C9clqTkLWxTUIwiPm33nUTEoyREBzZJOSa25c0iUpVDWieIlgYCpfynb7t4LAaHTfZbG04utmaAlJf",
	"m2xj3Ji4PIPvJ/aT5y4n0uUT0L66DrAgVhEN1mnZwT4MZJq86+R2FJ1MbHL+T4Sj+cGLDn7llCfKMMZv",
	"FHe23iFm65Ad6xv08vVznX18nNP+ezHR3KclptM52fsKqVV6eHo+fHP69vPLpu8Gb8QIq0xkrhSG1ITJ",
	"BQnVAakG6QPyZQ7khYfWCxICFEnnTM7AkAkzkBElifUkXo8vBt/libNqfwYSQlplkpzdSdBmzgsShkWY",
	"LfwavN1ROiTFjZCvzCqIPDXYP2SJyFy+V+A93C0WYjjAD6S8+iLlFcXUCbEYBIDUCCjtdim5LxCYIGHP",
	"iOVXYXt4z7PlsDGai4VoX0esPAgDwrpiHhM6RivYdRn5NDupp0u7Se3hgK2COJ1D+mOsnFdSeMZJUT11",
	"BAG3/mkUv+urFXW/ZW7WZD/aVYa/KG+rlokvA9vfT8xCplhokhsH7rFFQLuMJXtvvI72lbMJ+Yw6Ssi7",
	"oKKXnTBzGbdDoWYPVwie6i8161kk1LeAj8xZsb2al4Q72G6qsQ2J7PPQVeFzs0y/O93VlWt70vfs/PNf",
	"rweCPMgXzbgwTUj41yUieNlPDVcz7y5YVK3Xh0DZCxtPKCj+3+uE9VlIxFafscIizoAmpVYf0XFVWl4r",
	"CdqxuWWM3YTmfsOijjlR7xy9ri88Agn58pFhsUqy9Ugpqsc1nNf3MttgfomELZRvrfDR7p0Fvv/67Pq+",
	"RFjV7zNn517mFIsSz6GDeblgXJK0GqhG49u61YBbEL6uz8AyLsheaYSyn8CKk6eEy6lKiC+ICJepcBkY",
	"UoQxO5lyEJnpaurKS8eIg9f2TlZ3EvUbzyo2L/tbYjhOyX9B9P4AlrgSfk+MCxV6dxMWuuf6O7rJKJgx",
	"d0pnUR795+6tkXtj553FK69a8t0dHBy9IjhtXI9dtRXP5EQxnWF06jSki9nR7cyMD6K36yKsfw28s4Qa",
	"85pSKuKqqVlCf4+V3l+Z4FmYdYLWSj9pvFbFUozeZcTqziY4ujLDe/x7mi2HOeST0Eg/mFsQLuZrWPWp",
	"saZPixEibX1hirzJivHjjo231AG9pRxk77MSYCpkf4SFafYRQfRyFLytKy318uta0wcVuYuIF/Ta97eK",
	"JfVmR1vm2fDztFH0Rw9ibQH+vrX+XQ2u5XAHevuN0EredWlKHjsLfh9hQb5pVhSQ4cVL0D05ybLH1m4n",
	"Wb3aqhKKe/X2XM6i6Ass9G0FPqcFPaZDVvDh7eHwztDlaPm/AAAA///oxsz8zCwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
