name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.6'

      - name: Install test dependencies
        run: |
          go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.8.1
          go get github.com/onsi/ginkgo/v2/ginkgo/internal@v2.8.1
          go get github.com/onsi/ginkgo/v2/ginkgo/labels@v2.8.1
          go get github.com/onsi/ginkgo/v2@v2.8.1
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.8.1

      - name: Run unit tests
        run: make unit-tests

      - name: Run CI/CD tests
        run: make cicd-tests

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build \
            -t ghcr.io/pdaccess/ws:latest \
            -t ghcr.io/pdaccess/ws:${{ github.sha }} \
            .

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/pdaccess/ws:latest
          docker push ghcr.io/pdaccess/ws:${{ github.sha }}
